[build]
  # Assuming your frontend build output goes to a 'build' or 'dist' folder
  publish = "index.html" 
  # Path to your functions folder (must be outside the publish directory)
  functions = "proyek_2/ecommerce-app/netlify/functions" 

# Important: The redirect rule!
# This tells Netlify: "If a request starts with /api/, send it to the 'api' function."
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat" # The name of your function file (api.js)
  status = 200 # Use 200 for a successful proxy
  
